### ISSUE TITLE
How to set faceting option "searchable"?

### ISSUE THREAD

**Issue by bperun123** [k-yomo/terraform-provider-algolia#118]
### Terraform Version
- Terraform version: v1.2.5
- Provider version: v0.5.2

### Affected Resource(s)
algolia_index

### Terraform Configuration Files
```hcl
attributes_for_faceting = [
      "activationDate",
      "category",
      "collection",
      "..."
    ]
```

### Expected Behavior
![image](https://user-images.githubusercontent.com/67438899/180248970-2eaa8349-e83e-43c8-be49-1b9eb94f87db.png)
How to set this faceting option here?

### Actual Behavior
No option found in Terraform provider documentation.

Thanks in advance!!

**Comment by k-yomo** [comment]
@bperun123 
You can wrap the attribute name with `searchable()` like `"searchable(attribute3)`!
The parameters are passed to API through Go client, so you can reference the Algolia's API doc too.
https://www.algolia.com/doc/api-reference/api-parameters/attributesForFaceting/?client=go
