### ISSUE TITLE
Multiple virtual indicies don't work (Just the first one is "virtual")

### ISSUE THREAD

**Issue by bperun123** [k-yomo/terraform-provider-algolia#119]
### Terraform Version
- Terraform version: v1.2.5
- Provider version: v0.5.2

### Affected Resource(s)
- algolia_virtual_index

### Terraform Configuration Files
```hcl
resource "algolia_index" "primary_index" {
  name = "primary_index" 
}

resource "algolia_virtual_index" "virtual_index1" {
  name = "virtual_index1"
  primary_index_name = algolia_index.primary_index.name
}

resource "algolia_virtual_index" "virtual_index2" {
  name = "virtual_index2" 
  primary_index_name = algolia_index.primary_index.name
}
```

### Expected Behavior
virtual_index1 and virtual_index2 should be virtual.

### Actual Behavior
Just "virtual_index1" is virtual
![image](https://user-images.githubusercontent.com/67438899/180851785-8b3e777b-fdf7-4ddb-ad73-fb735b4a8f34.png)
![image](https://user-images.githubusercontent.com/67438899/180851917-0e0d8734-3636-48a2-82c3-e87a68c6987d.png)

### Steps to Reproduce
Just execute the code above

**Comment by k-yomo** [comment]
Oh..., I'll look into it🙏

**Comment by greg0ire** [comment]
@k-yomo I think I'm affected by this as well. Here is what @julienpa 's team witnessed in the logs:

> I can see a setSettings  on int_products_gb at ~11:15 with the replica virtual(int_products_gb_price_asc_alternate) . It’s removing a previous replica called int_products_gb_abtest_candidate and we have follow-up setSettings removing it for another one and so on...

`int_products_gb` is my main index, `int_products_gb_abtest_candidate` is a standard replica, and `int_products_gb_price_asc_alternate` a virtual one.

When I try with `TF_LOG=DEBUG`, I can see this:

```
PUT /1/indexes/int_products_gb/settings HTTP/1.1
Host: MLNQXJQTYA.algolia.net
User-Agent: Terraform/0.14.6 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-algolia/0.5.2;Algolia for Go (3.25.0);Go (go1.17.10)
Transfer-Encoding: chunked
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
X-Algolia-Api-Key: *********************************
X-Algolia-Application-Id: ***********
Accept-Encoding: gzip

62
{
 "replicas": [
  "int_products_gb_abtest_candidate",
  "virtual(int_products_gb_price_desc_alternate)"
 ]
}
```

That does not look too good indeed :sweat_smile:

**Comment by k-yomo** [comment]
Oh sorry..., yeah it reproduces on my end.
I'm looking into it🙇
