### ISSUE TITLE
No Task ID in output

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#127]
### Terraform Version
- Terraform version: v0.14.6
- Provider version: v0.5.3

### Expected Behavior
When using `TF_LOG=TRACE` (or even `DEBUG`), I should see polling requests to Algolia, as well as taskid

### Actual Behavior
`grep -i task infra/terraform/int/apply.txt|grep id` returns nothing

### Steps to Reproduce

Use `TF_LOG=TRACE` with any plan

### Important factoids

I can see some requests, just not the polling ones.

**Comment by k-yomo** [comment]
fmm, I can see the polling req/res.  If you grep `id` instead of the actual id, maybe you need to grep `taskID`.
```
---[ REQUEST ]---------------------------------------
GET /1/indexes/tf_provider_test_virtual_index2/task/215385613001 HTTP/1.1
Host: LBDZ3JJ70G-dsn.algolia.net
User-Agent: Terraform/0.15.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-algolia/dev;Algolia for Go (3.26.0);Go (go1.19)
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
X-Algolia-Api-Key: *********************************
X-Algolia-Application-Id: ***********
Accept-Encoding: gzip


-----------------------------------------------------: @caller=/Users/k-yomo/go/src/github.com/k-yomo/terraform-provider-algolia/internal/algoliautil/http.go:43 tf_provider_addr=registry.terraform.io/k-yomo/algolia tf_req_id=33d135a5-0e48-bab8-b9ac-c02f1d86ab79 tf_resource_type=algolia_virtual_index tf_rpc=ApplyResourceChange @module=algolia timestamp=2022-08-30T00:54:01.767+0900
2022-08-30T00:54:01.772+0900 [DEBUG] provider.terraform-provider-algolia: Algolia API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 45
Accept-Encoding: deflate, gzip
Access-Control-Allow-Origin: *
Cache-Control: no-store
Connection: keep-alive
Content-Disposition: inline; filename=a.txt
Content-Type: application/json; charset=UTF-8
Date: Mon, 29 Aug 2022 15:54:01 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Timing-Allow-Origin: *
X-Content-Type-Options: nosniff

{
 "status": "notPublished",
 "pendingTask": false
}
-----------------------------------------------------: tf_req_id=33d135a5-0e48-bab8-b9ac-c02f1d86ab79 tf_rpc=ApplyResourceChange @caller=/Users/k-yomo/go/src/github.com/k-yomo/terraform-provider-algolia/internal/algoliautil/http.go:55 @module=algolia tf_provider_addr=registry.terraform.io/k-yomo/algolia tf_resource_type=algolia_virtual_index timestamp=2022-08-30T00:54:01.772+0900
```

**Comment by greg0ire** [comment]
I really do literally grep `id`, I've done 2 grep because I wasn't sure if it would be `taskid` or `task_id`. Anyway, when I look at the output, it cycles through the usually "Still creating" stuff and never shows such requests.

An import factoid I left out is that the replicas I'm trying to create with this plan already exist. I created them manually while waiting for the resolution of #119, but somehow Terraform does not see them, and wants to create them, maybe I should have started with that. Maybe when applying, it does see them and the code supposed to refresh doesn't work.

Another important factoid is that this is happening on Algolia Metis, not Algolia Classic.

I'm not sure what to try next, maybe I should delete a replica, and try again to see if I get a task ID this time. My Metis instance is really slow at the moment, which is why I'm a bit relunctant to try many things, especially if they result in costly operations.

**Comment by k-yomo** [comment]
> An import factoid I left out is that the replicas I'm trying to create with this plan already exist. I created them manually while waiting for the resolution of https://github.com/k-yomo/terraform-provider-algolia/issues/119, but somehow Terraform does not see them, and wants to create them, maybe I should have started with that.

Oh I see.  Yeah, Terraform doesn't work like that, we need to import the resource first if we want to map the existing resource. 
https://www.terraform.io/cli/import

**Comment by greg0ire** [comment]
Ah yes, an import, I should have tried that. I'm interested in task ids because Metis is quite slow at the moment and @julienpa is asking me for task id so that Algolia folks can debug the slowness.

**Comment by greg0ire** [comment]
After the import, what happens is it plans to set `deletion_protection` to `true` for all the replicas I imported.
I don't think that's actually something that is managed by Algolia, I don't know that Algolia has a deletion protection. Because of that, I expected the change to be instant and ran the apply without `TF_LOG=TRACE` at first, but it started looping. I've restarted with `TF_LOG=TRACE` and now it's looping again, without any details. Here is an excerpt of the loop:

```
module.gb-b2c-app.module.rating_desc_replica.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_rating_desc, 3m20s elapsed]
module.gb-b2c-app.module.rating_desc_replica_alternate.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_rating_desc_alternate, 3m20s elapsed]
module.gb-b2c-app.module.price_desc_replica_alternate.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_price_desc_alternate, 3m20s elapsed]
module.gb-b2c-app.module.price_asc_replica_alternate.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_price_asc_alternate, 3m20s elapsed]
module.gb-b2c-app.module.price_asc_replica.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_price_asc, 3m30s elapsed]
module.gb-b2c-app.module.rating_desc_replica.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_rating_desc, 3m30s elapsed]
module.gb-b2c-app.module.rating_desc_replica_alternate.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_rating_desc_alternate, 3m30s elapsed]
module.gb-b2c-app.module.price_desc_replica_alternate.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_price_desc_alternate, 3m30s elapsed]
module.gb-b2c-app.module.price_asc_replica_alternate.algolia_virtual_index.product_index: Still modifying... [id=int_products_gb_price_asc_alternate, 3m30s elapsed]
```


Before the loop, I noticed these warnings:

```
2022/08/30 10:16:19 [WARN] Provider "registry.terraform.io/k-yomo/algolia" produced an invalid plan for module.gb-b2c-app.module.price_asc_replica.algolia_virtual_index.product_index, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .deletion_protection: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .timeouts: planned for existence but config wants absense
2022/08/30 10:16:19 [WARN] Provider "registry.terraform.io/k-yomo/algolia" produced an invalid plan for module.gb-b2c-app.module.rating_desc_replica_alternate.algolia_virtual_index.product_index, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .deletion_protection: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .timeouts: planned for existence but config wants absense
2022/08/30 10:16:19 [WARN] Provider "registry.terraform.io/k-yomo/algolia" produced an invalid plan for module.gb-b2c-app.module.price_desc_replica_alternate.algolia_virtual_index.product_index, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .deletion_protection: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .timeouts: planned for existence but config wants absense
2022/08/30 10:16:19 [WARN] Provider "registry.terraform.io/k-yomo/algolia" produced an invalid plan for module.gb-b2c-app.module.rating_desc_replica.algolia_virtual_index.product_index, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .deletion_protection: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .timeouts: planned for existence but config wants absense
2022/08/30 10:16:19 [WARN] Provider "registry.terraform.io/k-yomo/algolia" produced an invalid plan for module.gb-b2c-app.module.price_asc_replica_alternate.algolia_virtual_index.product_index, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .deletion_protection: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .timeouts: planned for existence but config wants absense
```

Not sure what to think about those.

**Comment by k-yomo** [comment]
Oh yeah, `terraform-provider-algolia` has the deletion protection to prevent deletion by mistake.

**Comment by k-yomo** [comment]
fmm, if it's looping without the req/res logs, it means the initial request to save the index setting may not be returning the task id and hanging.

**Comment by greg0ire** [comment]
What is this request made to ? Not Algolia, right? I mean, `deletion_protection` is not an index setting, is it?

**Comment by k-yomo** [comment]
No, `deleteion_protection` is not index setting in Algolia but the provider's internal thing.

**Comment by k-yomo** [comment]
Even if we don't have actuall diff, provider makes API request.

Oh sorry, maybe I put a bug in https://github.com/k-yomo/terraform-provider-algolia/pull/124

We use lock to avoid API request collision but missing unlocking when error.
https://github.com/k-yomo/terraform-provider-algolia/pull/128

**Comment by k-yomo** [comment]
@greg0ire 
Could you test again with the v0.5.4?🙏

**Comment by greg0ire** [comment]
I'm trying to upgrade but I have this:

```
Could not retrieve the list of available versions for provider k-yomo/algolia:
no available releases match the given constraints 0.5.4
```

Maybe it takes some time…

**Comment by greg0ire** [comment]
Bad news, that doesn't seem to fix it, the loop is still happening.

**Comment by greg0ire** [comment]
In addition to this, Terraform does not see that it should create the replica that I deleted. That replica does not appear in the list of resources that get refreshed.

**Comment by greg0ire** [comment]
When I try at level `WARN` to get less output, I notice this warning just before the loop: `2022-08-30T14:00:15.139+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"`. Not sure how important it is.

**Comment by k-yomo** [comment]
Are you running terraform command on M1 mac?
If so, the below issue might be related...!
https://github.com/hashicorp/terraform-provider-aws/issues/16073#issuecomment-1206853583

**Comment by greg0ire** [comment]
I'm using Linux, but maybe I should try running this in the CI to see if I get different results.

**Comment by greg0ire** [comment]
> In addition to this, Terraform does not see that it should create the replica that I deleted. That replica does not appear in the list of resources that get refreshed.

OK I'm really dumb, we don't have a definition for that sort. We have a replica for price desc, another for price asc, another for rating desc, and I completed that pattern by manually creating a replica for rating asc :facepalm: … sorry for the noise. I'm going to clean this up and maybe the situation will become clearer after that.

**Comment by k-yomo** [comment]
@greg0ire 
Hi!  Is this issue happening?

**Comment by greg0ire** [comment]
I'm on holidays until next week, will re-evaluate this when I'm back :)

**Comment by greg0ire** [comment]
There has been work on Metis, and I suspect this issue was due to a bug in that architecture. Let's close this :slightly_smiling_face:
