### ISSUE TITLE
attributes_to_highlight not applied

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#136]
### Terraform Version
- Terraform version: v0.14.16
- Provider version: v0.5.4

### Affected Resource(s)

- algolia_index
- algolia_virtual_index

### Terraform Configuration Files
Copy-paste your Terraform configurations here
```hcl
  highlight_and_snippet_config {
    attributes_to_highlight = []
    highlight_pre_tag       = "<em>"
    highlight_post_tag      = "</em>"
  }
```

### Expected Behavior
`attributes_to_highlight` should be set to `[]

### Actual Behavior

`attributes_to_highlight` is set to null

### Steps to Reproduce

Create an index with the above configuration.

### Important Factoids

- I apparently did not get back to you after https://github.com/k-yomo/terraform-provider-algolia/issues/40#issuecomment-940176158 (sorry)
- setting an attribute works, it's just setting to an empty array that does not work.
- manually setting `attributes_to_highlight` to `[]` via the dashboard results in an empty plan
- setting `attributes_to_highlight` to null also results in a empty plan

### References

https://github.com/k-yomo/terraform-provider-algolia/issues/40

**Comment by k-yomo** [comment]
I confirmed it reproduces.
It seems the behaviour is the Go API client's bug so opened an issue on the client repo!
https://github.com/algolia/algoliasearch-client-go/issues/704

**Comment by greg0ire** [comment]
Thanks a lot, I should be able to try it within a week :crossed_fingers:

**Comment by greg0ire** [comment]
@k-yomo do you think this should (Terraform not detecting changes) become a separate bug, or is it something that would not happen on a freshly-created index?

**Comment by greg0ire** [comment]
Ah maybe that was it yeah. Once I've done the change, I will try using `null` to check if Terraform detects that it should change.
