### ISSUE TITLE
Feature: region setting in provider

### ISSUE THREAD

**Issue by dotSource-bke** [k-yomo/terraform-provider-algolia#139]
### Terraform Version
- Terraform version: v#.#.#
- Provider version: v#.#.#

### Terraform Configuration Files
```hcl
provider "algolia" {
  app_id  = "my-app-id"
}
```

### Expected Behavior
Ability to set Region in provider

### Actual Behavior
Default region is selected implicitly

### Steps to Reproduce
- Creat algolia app with settings located on a region *different* to the provider default
- Apply terraform configuration

### Important Factoids
An implementation example can be found on:
https://github.com/dotSource-bke/terraform-provider-algolia/blob/59a1ac41ab2368d76a0199543b1dba4e5d19531f/internal/provider/provider.go#L40
### References
none

**Comment by k-yomo** [comment]
Hi, thanks for reporting!!
Do they have region in search config?
https://github.com/algolia/algoliasearch-client-go/blob/master/algolia/search/configuration.go#L12-L23

**Comment by dotSource-bke** [comment]
Hi,
I saw you already address the issue with a region setting for the suggestion indices.
https://github.com/k-yomo/terraform-provider-algolia/blob/d390eda3a7d9055b4d1212c455a6bd7d13b1ec92/internal/provider/resource_query_suggestions.go#L36
This covers the feature we need. Sorry to bother you. We will now be able to switch back to your provider.
Thank you for your awesome work!
