### ISSUE TITLE
Why Read-Only algolia_virtual_index languages_config.index_languages ??

### ISSUE THREAD

**Issue by somen440** [k-yomo/terraform-provider-algolia#142]
The property says Read-Only in the documentation
https://registry.terraform.io/providers/k-yomo/algolia/latest/docs/resources/virtual_index#nested-schema-for-languages_config

I was able to confirm that there is no problem in manual change confirmation and operation from the console.
Why Read-Only algolia_virtual_index languages_config.index_languages ??

**Comment by greg0ire** [comment]
That's weird, I don't observe the same thing at all. Are you sure your replica is a virtual one?

![Screenshot 2022-11-09 at 17-13-27 Index Algolia](https://user-images.githubusercontent.com/657779/200882311-75128e01-9e1b-4b6f-bf75-5c556671dac2.png)

**Comment by somen440** [comment]
Here's what it looks like on my console.

![スクリーンショット 2022-11-10 9 31 08](https://user-images.githubusercontent.com/10706586/200971247-b9a8627e-d34c-4521-8adf-0a360fbc641e.png)


![スクリーンショット 2022-11-10 9 31 14](https://user-images.githubusercontent.com/10706586/200971194-a4d931f8-d2c7-4885-b9b3-e2b5e0728a27.png)

**Comment by somen440** [comment]
Maybe "virtual index" and "replica" are different things ...... ?

**Comment by k-yomo** [comment]
Yes, you can use `algolia_index` resource for standard replica by setting `primary_index_name` field!
https://registry.terraform.io/providers/k-yomo/algolia/latest/docs/resources/index#primary_index_name

**Comment by somen440** [comment]
Oh ! Sorry ... 🙇
