### ISSUE TITLE
Cannot terraform rule "An argument named "facetFilters" is not expected here."

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#208]
### Terraform Version
- Terraform version: v1.4.4
- Provider version: v0.5.7

### Affected Resource(s)

- algolia_rule

### Terraform Configuration Files
Copy-paste your Terraform configurations here
```hcl
resource "algolia_rule" "brand-name" {
  index_name = var.index_name
  object_id  = "remove-laser"

  conditions {
    anchoring    = "is"
    pattern      = "laser"
    alternatives = false
  }

  consequence {
    params {
      facetFilters = ["brand_name:-Laser"]
    }
  }

  description = "Removes all records with the brand name Laser from searches for laser"
}
```

### Expected Behavior

[The docs](https://registry.terraform.io/providers/k-yomo/algolia/latest/docs/resources/rule#nested-schema-for-consequence) say this about `params`:

>  Additional search parameters. Any valid search parameter is allowed. Specific treatment is applied to these fields: query, automaticFacetFilters, automaticOptionalFacetFilters

`facetFilters` is definitely a valid search parameter: https://www.algolia.com/doc/api-reference/api-parameters/facetFilters/

A rule looking like this should be terraformed:

```json
{
  "condition": {
    "anchoring": "is",
    "pattern": "laser",
    "alternatives": false
  },
  "consequence": {
    "params": {
      "facetFilters": [
        "brand_name:-Laser"
      ]
    }
  },
  "description": "Removes all records with the brand name Laser from searches for laser",
  "objectID": "remove-laser"
}
```

### Actual Behavior

I'm getting an error saying

> An argument named "facetFilters" is not expected here.

### Steps to Reproduce

Run `terraform plan` with the above

### Important Factoids

None

### References

None

**Comment by k-yomo** [comment]
@greg0ire 
Oh you're right.  It seems we should change the type of `params` to either JSON `string` or `map` to fix the problem and be more flexible.

**Comment by greg0ire** [comment]
Thank you! Will try that next week!
