### ISSUE TITLE
Extra level when terraforming rule

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#211]
### Terraform Version
- Terraform version: v1.4.4
- Provider version: v0.6.0

### Affected Resource(s)

- algolia_rule

### Terraform Configuration Files
Copy-paste your Terraform configurations here
```hcl
terraform {
  required_providers {
    algolia = {
      source = "k-yomo/algolia"
    }
  }
}

resource "algolia_rule" "brand-name" {
  index_name = var.index_name
  object_id  = "remove-laser"

  conditions {
    anchoring    = "is"
    pattern      = "laser"
    alternatives = false
  }

  consequence {
    params_json = jsonencode({
      facetFilters = ["brand_name:-Laser"]
    })
  }

  description = "Removes all records with the brand name Laser from searches for laser"
}
```

### Expected Behavior

The following rule should have been terraformed

```json
{
  "conditions": [
    {
      "alternatives": false,
      "anchoring": "is",
      "pattern": "laser"
    }
  ],
  "consequence": {
    "params": {
      "facetFilters": [
          "brand_name:-Laser"
      ]
    }
  },
  "description": "Removes all records with the brand name Laser from searches for laser",
  "enabled": true,
  "objectID": "remove-laser"
}
```

### Actual Behavior
The following rule was created instead:

```
{
  "conditions": [
    {
      "alternatives": false,
      "anchoring": "is",
      "pattern": "laser"
    }
  ],
  "consequence": {
    "params": {
      "facetFilters": [
        [
          "brand_name:-Laser"
        ]
      ]
    }
  },
  "description": "Removes all records with the brand name Laser from searches for laser",
  "enabled": true,
  "objectID": "remove-laser"
}
```

Notice the extra nesting under `facetFilters`

### Steps to Reproduce

Apply a plan with such a rule above

### Important Factoids

n/a

### References

n/a

**Comment by k-yomo** [comment]
It seems Algolia converts the condition to nested array?.
https://github.com/algolia/algoliasearch-client-go/blob/f570885dd174cddc6b8fd32e4d3eb01da12caab5/algolia/opt/facet_filters.go#L31-L44

Probably because they store the condition in the nested array to be able to handle AND/OR filters.

**Comment by k-yomo** [comment]
@greg0ire 
We can't do anything about it on terraform provider side, so please update the definition or use `filters` which is always string!
https://www.algolia.com/doc/api-reference/api-parameters/filters/
