### ISSUE TITLE
Extra "hide" attribute when introspecting rule

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#212]
### Terraform Version
- Terraform version: v1.4.4
- Provider version: v0.6.0

### Affected Resource(s)

- `algolia_rule`

### Terraform Configuration Files
Copy-paste your Terraform configurations here
```hcl
terraform {
  required_providers {
    algolia = {
      source = "k-yomo/algolia"
    }
  }
}

resource "algolia_rule" "brand-name" {
  index_name = var.index_name
  object_id  = "remove-laser"

  conditions {
    anchoring    = "is"
    pattern      = "laser"
    alternatives = false
  }

  consequence {
    params_json = jsonencode({
      facetFilters = [["brand_name:-Laser"]]
    })
  }

  description = "Removes all records with the brand name Laser from searches for laser"
}
```

### Expected Behavior

After applying, the plan should be empty

### Actual Behavior
The following plan was created instead:

```
  # redacted.algolia_rule.brand-name is tainted, so must be replaced
-/+ resource "algolia_rule" "brand-name" {
      ~ id          = "remove-laser" -> (known after apply)
        # (4 unchanged attributes hidden)
      ~ conditions {
            # (3 unchanged attributes hidden)
        }
      ~ consequence {
          - hide        = [] -> null
            # (1 unchanged attribute hidden)
        }
    }
```

It seems that an extra, useless consequence consisting in `hide = []` is introspected by `terraform-provider-algolia`. It is not present in the JSON of the rule when using the rule dashboard to view it.

### Steps to Reproduce

Apply a plan with such a rule above

### Important Factoids

I do not observe the issue on all the Algolia apps I manage.

### References

n/a

**Comment by greg0ire** [comment]
Maybe this is caused by this code block: https://github.com/k-yomo/terraform-provider-algolia/blob/d46b4fc84b81cc8a1c5e9b814617b6ef5c6a19c1/internal/provider/resource_rule.go#L482C1-L486C40

**Comment by greg0ire** [comment]
ping @k-yomo :pray:

**Comment by k-yomo** [comment]
Sorry for the late reply.
fmm, I can't reproduce it...!

Yeah the code you shared looks suspicious but if that's the case, empty array will be also set for the other fields.
https://github.com/k-yomo/terraform-provider-algolia/blob/main/internal/provider/resource_rule.go#L468-L480

**Comment by greg0ire** [comment]
Yeah it's weird… I don't think the fact that we have `[]interface{}` makes any difference here, does it?
Also, what's weird is that out of the 30 apps I have, it only happens on 2 production apps, which are the biggest I have.

**Comment by greg0ire** [comment]
Another thing I forgot to mention: the terraforming itself times out every time I try. I will include the output.

**Comment by greg0ire** [comment]
After resolving the timeout issue, it works great 👍 Sorry for the wrong report!
