### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#29]
Hi!

After reading the issue template, I just created an issue at https://discuss.hashicorp.com/t/how-to-customize-configuration-for-an-algolia-replica/26976

I'm not sure if this is really what you want though, as this is a fork of `hashicorp/terraform-provider-scaffolding`. Maybe you didn't notice there was an issue template and don't actually want people to post there?

**Comment by k-yomo** [comment]
Thank you for creating an issue!
Yeah I didn't notice it. Posting issue on Github would be better, I'll fix contribution guide!

**Comment by k-yomo** [comment]
To change `custom_ranking ` of a replica, you can have another resource for replica.
```terraform
resource "algolia_index" "my_replica" {
  name = "my_replica"

  ranking_config {
    custom_ranking = [
      // modified ranking
    ]
  }
}

resource "algolia_index" "my_primary_index" {
ranking_config {
    custom_ranking = [
      "asc(has_ranking_malus)",
      "desc(score_a)",
      "asc(price)",
      "desc(has_free_delivery)",
      "desc(rating)",
      "desc(rating_count)"
    ]
    replicas = [
      algolia_index.my_replica.name
    ]
  }
}
```

If the replica is already created, you need to import it.
```sh
terraform import algolia_index.my_replica my_replica

```

**Comment by greg0ire** [comment]
Will try, thanks a lot!

**Comment by greg0ire** [comment]
Another question: we have 3 replicas, and one of my colleagues just made a PR to change 2 of them to virtual replicas. Should I use `"virtual(${algolia_index.my_replica.name})"` for those? Is it going to work as intended?

**Comment by greg0ire** [comment]
Answering my own question: it does work :)

**Comment by k-yomo** [comment]
I'll close this issue, If you face  another issue, please create a new one!
