### ISSUE TITLE
highlight_and_snippet_config not imported

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#40]
### Terraform Version
- Terraform version: v0.14.16
- Provider version: v0.2.1

### Affected Resource(s)
- algolia_index

### Terraform Configuration Files

This has to do with the import so… irrelevant?

### Expected Behavior

After a refactoring, resources name can change. After running `terragrunt state rm old-name && terragrunt import new_name index_name`, the plan should be empty.

### Actual Behavior
The plan contains the following:

```
      + highlight_and_snippet_config {
          + attributes_to_highlight               = [
              + "model_id",
            ]
          + highlight_post_tag                    = "</em>"
          + highlight_pre_tag                     = "<em>"
          + restrict_highlight_and_snippet_arrays = false
          + snippet_ellipsis_text                 = "…"
        }
```

### Steps to Reproduce

1. create an index resource with the following block:
```
      + highlight_and_snippet_config {
          + attributes_to_highlight               = [
              + "model_id",
            ]
          + highlight_post_tag                    = "</em>"
          + highlight_pre_tag                     = "<em>"
          + restrict_highlight_and_snippet_arrays = false
          + snippet_ellipsis_text                 = "…"
        }
```
2. apply the plan
3. remove the resource from the state
4. import the resource from Algolia

**Comment by k-yomo** [comment]
Thank you for opening the issue! Let me try to reproduce and fix it!
Also, sorry I missed #38 for a long time, I'll check it as well soon.

**Comment by greg0ire** [comment]
One of my colleagues pointed out the configuration is not listed in https://github.com/k-yomo/terraform-provider-algolia/blob/10a97724d87323c7cd686c7792c4a4bbceb5e0b5/internal/provider/resource_index.go#L663-L733

**Comment by greg0ire** [comment]
Thank you so much, I will test that soon :)
