### ISSUE TITLE
Facet changes not applied

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#79]
### Terraform Version
- Terraform version: v0.14.6
- Provider version: v0.2.9

### Affected Resource(s)

- algolia_index

### Terraform Configuration Files
Copy-paste your Terraform configurations here
```hcl
  ~ resource "algolia_index" "product_index" {
        id                     = "int_products_gb_rating_desc"
        name                   = "int_products_gb_rating_desc"
        # (4 unchanged attributes hidden)
      ~ attributes_config {
          ~ attributes_for_faceting  = [
              - "filterOnly(private_sale_ids)",
                # (31 unchanged elements hidden)
            ]
            # (3 unchanged attributes hidden)
        }
        # (9 unchanged blocks hidden)
    }
```

### Expected Behavior
The facets should change (`private_sale_ids`)

### Actual Behavior
Terraform keeps polling, but the change does not appear to happen. Using `TF_LOG=DEBUG`, I see this:

```
---[ REQUEST ]---------------------------------------
PUT /1/indexes/int_products_gb_rating_desc/settings HTTP/1.1
Host: MLNQXJQTYA.algolia.net
User-Agent: Terraform/0.14.6 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-algolia/0.2.9;Algolia for Go (3.23.0);Go (go1.17.7)
Transfer-Encoding: chunked
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
X-Algolia-Api-Key: *********************************
X-Algolia-Application-Id: ***********
Accept-Encoding: gzip

5ea
{
 "advancedSyntax": false,
 "advancedSyntaxFeatures": [
  "exactPhrase",
  "excludeWords"
 ],
 "allowTyposOnNumericTokens": false,
 "alternativesAsExact": [
  "ignorePlurals",
  "singleWordSynonym"
 ],
 "attributeCriteriaComputedByMinProximity": true,
 "attributesToHighlight": null,
 "attributesToRetrieve": [
  "*"
 ],
 "attributesToSnippet": null,
 "customRanking": [
  "desc(has_ranking_malus)",
  "desc(score_a)",
  "asc(price)",
  "desc(has_free_delivery)",
  "desc(rating)",
  "desc(rating_count)"
 ],
 "decompoundQuery": true,
 "distinct": 1,
 "enableRules": true,
 "exactOnSingleWordQuery": "attribute",
 "highlightPostTag": "\u003c/em\u003e",
 "highlightPreTag": "\u003cem\u003e",
 "hitsPerPage": 60,
 "ignorePlurals": [
  "en"
 ],
 "maxFacetHits": 10,
 "maxValuesPerFacet": 1000,
 "minProximity": 1,
 "minWordSizefor1Typo": 4,
 "minWordSizefor2Typos": 8,
 "paginationLimitedTo": 20000,
 "queryLanguages": [
  "en"
 ],
 "queryType": "prefixLast",
 "ranking": [
  "desc(rating_weighted)",
  "typo",
  "geo",
  "words",
  "filters",
  "proximity",
  "attribute",
  "exact",
  "custom"
 ],
 "removeStopWords": [
  "en"
 ],
 "removeWordsIfNoResults": "allOptional",
 "replaceSynonymsInHighlight": false,
 "replicas": null,
 "responseFields": [
  "*"
 ],
 "restrictHighlightAndSnippetArrays": false,
 "snippetEllipsisText": "",
 "sortFacetValuesBy": "count",

 "unretrievableAttributes": [
  "prices.per_item.legacy_unit",
  "unit_price",
  "has_ranking_malus",
  "rating_rounded_down",
  "retail_price",
  "best_offer",
  "unit_type",
  "ean",
  "is_sample",
  "detail_price",
  "rating_weighted",
  "has_sample",
  "model_titles",
  "product_update_time",
  "legacy_unit",
  "article_update_time",
  "document_update_time",
  "mpn"
 ]
}

0


-----------------------------------------------------: timestamp=2022-04-05T15:10:14.474+0200
2022-04-05T15:10:14.560+0200 [INFO]  plugin.terraform-provider-datadog_v3.6.0: 2022/04/05 15:10:14 [DEBUG] Datadog API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 14
Alt-Svc: clear
Cache-Control: no-cache
Content-Security-Policy: frame-ancestors 'self'; report-uri https://logs.browser-intake-datadoghq.com/api/v2/logs?dd-api-key=pube4f163c23bbf91c16b8f57f56af9fc58&dd-evp-origin=content-security-policy&ddsource=csp-report&ddtags=site%3Adatadoghq.eu
Content-Type: application/json
Date: Tue, 05 Apr 2022 13:10:14 GMT
Pragma: no-cache
Strict-Transport-Security: max-age=15724800;
Via: 1.1 google
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Ratelimit-Limit: 12000
X-Ratelimit-Period: 60
X-Ratelimit-Remaining: 11924
X-Ratelimit-Reset: 46

{
 "valid": true
}
```

I would expect the `PUT` request to contain something about facets

### Steps to Reproduce

Create a plan that changes facets to remove them.
Try applying that plan.

### Important Factoids

Nothing comes to mind. I don't remember trying this in the past though

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by greg0ire** [comment]
cc @k-yomo :)

**Comment by k-yomo** [comment]
@greg0ire 
Isn't the index virtual index?
If so, we can't change on a virtual replica.  If not, I'll look into it🙏
https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/in-depth/replicas/#unsupported-parameters

**Comment by greg0ire** [comment]
HI @k-yomo , it's not a virtual replica no (but it is a replica). I can check tomorrow but I think this also affects primary indices, not just replicas.

**Comment by greg0ire** [comment]
Hello @k-yomo ! Today, I tried removing a facet through the UI, to see if the opposite issue exists (Terraform not adding a facet), and it seems to: again, `attributesForFaceting` is not mentioned in the `PUT` request.

**Comment by greg0ire** [comment]
This piece of code looks kind of suspicious:

https://github.com/k-yomo/terraform-provider-algolia/blob/9d9be72d2be7539b3a55a7d9df79e925b52fb2bd/internal/provider/resource_index.go#L689-L692

It seems to say: if the index has a primary, then it's virtual, but that's not correct, is it?

**Comment by greg0ire** [comment]
I've taken a look at the logs again (with max verbosity), and I can see `"virtual": true` appear for indices that are not supposed to be virtual.

**Comment by k-yomo** [comment]
Sorry for the late reply...!

> It seems to say: if the index has a primary, then it's virtual, but that's not correct, is it?

Yeah, that's true.  It might be a normal replica.

**Comment by greg0ire** [comment]
> Sorry for the late reply...!

No worries, I know what open-source is, it's already amazing to get that level of support from you :heart:

**Comment by k-yomo** [comment]
@greg0ire 
I released [v.0.2.11](https://github.com/k-yomo/terraform-provider-algolia/releases/tag/v0.2.11)!🙌

It should fix the problem🙏  Sorry for the late fix and thanks for opening the issue and PR!!

**Comment by greg0ire** [comment]
Thanks! Will try ASAP!
