### ISSUE TITLE
Feature request: add support for Terraforming relevancy strictness

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#91]
Looks like it's not currently supported, but the code is already there, just commented out: 

https://github.com/k-yomo/terraform-provider-algolia/blob/8f319f77e8f8143d6b0caf43ae6326c11f1d0e92/internal/provider/data_source_index.go#L81-L87

It depends on a merge request that has been merged and release in v3.20.0 of the golang client, so I think that requirement is fulfilled: https://github.com/k-yomo/terraform-provider-algolia/blob/f4f75f406d64a7e2c0ba1a6731d66db10d9fa305/go.mod#L6

**Comment by k-yomo** [comment]
Thanks again for opening the issue and PR!
I just released [v0.3.0](https://github.com/k-yomo/terraform-provider-algolia/releases/tag/v0.3.0)!
