### ISSUE TITLE
Terraforming virtual indices is not idempotent

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#94]
### Terraform Version
- Terraform version: v0.14.6
- Provider version: v0.3.0

### Affected Resource(s)

- `algolia_index`

### Terraform Configuration Files
Copy-paste your Terraform configurations here
```hcl
terraform {
  required_providers {
    algolia = {
      source  = "k-yomo/algolia"
      version = "0.3.0"
    }
  }
}

resource "algolia_index" "product_index" {
  name = var.index_name

  typos_config {
    min_word_size_for_1_typo      = 4
    min_word_size_for_2_typos     = 8
    typo_tolerance = "min"
  }

  pagination_config {
    hits_per_page         = 60
    pagination_limited_to = 20000
  }

  faceting_config {
    max_values_per_facet = 1000
  }

  languages_config {
    ignore_plurals_for = [var.language]
    remove_stop_words_for = [var.language]
    query_languages       = [var.language]
  }

  advanced_config {
    response_fields                              = ["*"]
    attribute_criteria_computed_by_min_proximity = true
    distinct                                     = 1
    attribute_for_distinct                       = "article_id" # this will probably be ignored, but is mandatory when you specify "distinct"
  }

  highlight_and_snippet_config {
    attributes_to_highlight = []
    highlight_pre_tag       = "<em>"
    highlight_post_tag      = "</em>"
  }

  attributes_config {
    attributes_to_retrieve = ["*"]

    unretrievable_attributes = [
      "document_update_time",
      "ean",
      "has_ranking_malus",
      "model_titles",
      "mpn",
      "rating_rounded_down",
      "rating_weighted",
    ]
  }

  query_strategy_config {
    remove_words_if_no_results = "allOptional"
    query_type                 = "prefixLast"
    alternatives_as_exact = [
      "ignorePlurals",
      "singleWordSynonym"
    ]
    advanced_syntax_features = [
      "exactPhrase",
      "excludeWords",
    ]
  }

  ranking_config {
    custom_ranking       = var.custom_ranking
    relevancy_strictness = 0
  }

  virtual = true
}

```

### Expected Behavior

Terraforming this should be idempotent

### Actual Behavior

Planning and applying works, but planning again results in the following plan:

```
  # module.it-b2c-pprod-app.module.rating_desc_replica_alternate.algolia_index.product_index will be updated in-place
  ~ resource "algolia_index" "product_index" {
        id                     = "pprod_products_it_rating_desc_alternate"
        name                   = "pprod_products_it_rating_desc_alternate"
        # (4 unchanged attributes hidden)


      ~ attributes_config {
          ~ attributes_for_faceting  = [
              - "banner.alternate.categories",
              - "banner.categories",
              - "catalog_attribute",
              - "catalog_attribute_facet",
              - "categories.l1.id",
              - "categories.l2",
              - "categories.l2.id",
              - "categories.l3",
              - "categories.l3.id",
              - "category_last",
              - "filterOnly(categories.l0.id)",
              - "filterOnly(commercial_operation_ids)",
              - "filterOnly(model_id)",
              - "has_1day_delivery",
              - "has_3x_payment",
              - "has_free_delivery",
              - "has_pro_conditions",
              - "has_relay_delivery",
              - "is_eco_responsible",
              - "is_local",
              - "is_mmf",
              - "prices.per_item.actual_price.with_vat.as_float",
              - "prices.per_item.actual_price.without_vat.as_float",
              - "prices.per_m2.actual_price.with_vat.as_float",
              - "prices.per_m2.actual_price.without_vat.as_float",
              - "rating_rounded_down",
              - "searchable(brand_name)",
              - "searchable(categories.l0)",
              - "searchable(categories.last)",
              - "searchable(categories.last_id)",
              - "searchable(price)",
              - "searchable(seller_name)",
            ]
          ~ searchable_attributes    = [
              - "model_titles",
              - "default_title",
              - "brand_name",
              - "categories.last",
              - "unordered(model_descriptions)",
              - "unordered(catalog_attribute)",
              - "model_id",
              - "me_id",
              - "sku",
              - "categories.l2.id",
              - "categories.l3.id",
              - "mpn",
              - "ean",
            ]
            # (2 unchanged attributes hidden)
        }







      ~ ranking_config {
          ~ ranking              = [
              - "typo",
              - "geo",
              - "words",
              - "filters",
              - "proximity",
              - "attribute",
              - "exact",
              - "custom",
            ]
            # (3 unchanged attributes hidden)
        }

      ~ typos_config {
          ~ disable_typo_tolerance_on_attributes = [
              - "ean",
              - "me_id",
              - "model_descriptions",
              - "model_id",
              - "mpn",
              - "sku",
            ]
            # (5 unchanged attributes hidden)
        }
        # (7 unchanged blocks hidden)
    }
```

Applying this is fast and does not result in errors, so this is slightly different from #59 

### Steps to Reproduce

Terraform a virtual index as described in the documentation

### Important Factoids

Nothing comes to mind.

### References

#59 looks similar

**Comment by k-yomo** [comment]
Oh I see.
It seems like the fields are set by Algolia's response, but since we don't set the field in tf file, the diff is shown. 
https://github.com/k-yomo/terraform-provider-algolia/blob/main/internal/provider/resource_index.go#L693

Let me fix it not to set those fields for virtual index.


Ideally, those fields should be `computed` field which can't be set but keep updated when the main index is updated.  To do so, we may need new resource for virtual index.

**Comment by greg0ire** [comment]
> It might be better to have new resource for virtual index.

Yes, I think it might make sense.
At first, I had a `product-index` variable that was able to let me create both standard indexes or virtual indexes, but then, after a first successful run, I got errors from Algolia's API because I was trying to modify a virtual index to set `ranking`, among other things. I refactored the virtual index creation in a separate module that sets only the fields that should be set, and it works better now. Having a new resource would have caught this issue earlier, and would have forced me to do that refactoring earlier, which would have been a good thing.

**Comment by k-yomo** [comment]
I see..!
Let me fix it first by just ignoring unsupported fields for virtual index, then I'll create a new resource for virtual index in a separate PR.

**Comment by greg0ire** [comment]
That will make the migration easier 👍

**Comment by k-yomo** [comment]
@greg0ire 
I just released [v0.3.1](https://github.com/k-yomo/terraform-provider-algolia/releases/tag/v0.3.1), i hope it would solve the issue!

**Comment by greg0ire** [comment]
@k-yomo it's better! Now I only have `attribute_for_distinct` that appears in the diff.
I noticed in the UI that it is inherited and that it makes no sense to specify it, yet when I do not specify it, I can no longer specify `distinct`, which is not inherited. I get the following error: `advanced_config.0.distinct`: all of `advanced_config.0.attribute_for_distinct,advanced_config.0.distinct` must be specified. Do you want me to raise this in a separate issue?

**Comment by k-yomo** [comment]
Oh sorry, I missed to handle it.🙏
I'll fix to be able to specify only `distinct` without `attribute_for_distinct ` in https://github.com/k-yomo/terraform-provider-algolia/pull/97.

We don't need separate issue!

**Comment by k-yomo** [comment]
Just released [v0.3.2](https://github.com/k-yomo/terraform-provider-algolia/releases/tag/v0.3.2) that includes the above fix!🙌

**Comment by greg0ire** [comment]
My plan is now empty :ok_hand: ! Thanks a lot @k-yomo !

**Comment by k-yomo** [comment]
I added dedicated resource for virtual index, please check it out!
https://registry.terraform.io/providers/k-yomo/algolia/latest/docs/resources/virtual_index

**Comment by greg0ire** [comment]
Will do!
